# -*- coding: utf-8 -*-
"""Untitled144.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14phXA9CJq6qhHBZkEyg6wBuakSJUJNAP
"""

from google.colab import drive
drive.mount('/content/drive')

!unzip -o "/content/drive/MyDrive/deepfashion2-m-10k.v2i.yolov11.zip" -d "/content/deepfashion2"

!pip install torch torchvision ultralytics opencv-python numpy onnx onnxruntime-gpu roboflow opencv-python

import os
import time
import warnings
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader, Dataset
from torchmetrics.detection.mean_ap import MeanAveragePrecision
from torchvision import transforms
from PIL import Image
from ultralytics import YOLO
import datetime
import shutil
import cv2

import yaml

with open("/content/deepfashion2/data.yaml") as f:
    data = yaml.safe_load(f)

classes = data["names"]
num_classes = len(classes)

print(classes)
print(num_classes)

from google.colab import drive
drive.mount('/content/drive')

"""Training Loop"""

def train_yolo_model(epochs=80, batch_size=16, img_size=640, lr0=0.01,**kwargs):
    # Check for CUDA availability
    device = '0' if torch.cuda.is_available() else 'cpu'

    # Define timestamp for unique model naming
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    run_name = f'train_{timestamp}'
    stage_name = kwargs.get('stage_name')
    base_dir = f"/content/drive/MyDrive/YOLO_Project/{stage_name}"
    model_save_dir = os.path.join(base_dir, 'model')

    model_input = kwargs.get('model', 'yolo11m.pt')
    model = YOLO(model_input)

    # Train the model
    results = model.train(
        data="/content/deepfashion2/data.yaml",
        epochs=epochs,
        batch=batch_size,
        imgsz=img_size,
        patience=50,
        save=True,
        device=device,
        project=os.path.join(base_dir, 'runs'),
        name=run_name,
        lr0=lr0,
        lrf=0.01,
        cos_lr=kwargs.get('cos_lr', False),
        optimizer=kwargs.get('optimizer', 'auto'),
        plots=True,
        save_period=5,
        augment=True,
        verbose=True,
        freeze=kwargs.get('freeze', None),
        fliplr=0.5,    # Horizontal flip probability
        flipud=0.1,    # Vertical flip probability (use 0 if orientation matters)
        mosaic=1.0,    # Mosaic augmentation
        mixup=0.1,     # Mixup augmentation
        copy_paste=0.1 # Copy-paste augmentation
    )

    # Save the model
    model_save_path = os.path.join(model_save_dir, f"{stage_name}_{timestamp}.pt")

    try:
        model.model.save(model_save_path)
    except AttributeError:
        try:
            model.save(model_save_path)
        except Exception:
            best_model_path = os.path.join(base_dir, 'runs', run_name, 'weights', 'best.pt')
            if os.path.exists(best_model_path):
                shutil.copy2(best_model_path, model_save_path)

    return model

"""F2 Score"""

base_dir = "/content/drive/MyDrive/YOLO_Project"
def validate_model(model):
    metrics = model.val(
        data="/content/deepfashion2/data.yaml",
        split='val',
        project=os.path.join(base_dir, 'runs'),
        name='val'
    )

    # Calculate F1 score
    f1_score = 2 * metrics.box.precision * metrics.box.recall / (metrics.box.precision + metrics.box.recall + 1e-6)

    return metrics

"""Inference mode"""

from datetime import datetime

"""  Stage 1"""

def main():
    # Define timestamp for this training run
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    # Train model
    model = train_yolo_model(epochs=200,warmup_epochs=5, batch_size=16,stage_name = "stage1")

    if model is not None:
        validate_model(model)
main()

from ultralytics import YOLO


model_path = "/content/drive/MyDrive/YOLO_Project/stage1/runs/train_20260614_081102/weights/last.pt"


model = YOLO(model_path)

model.train(resume=True)